### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by tattivitorino** [samikrc/CordovaSQLite#3]
My friend, your plugin is missing the package.json which makes installing it impossible!

**Comment by samikrc** [comment]
Hello, thanks for logging the issue. You know: this used to work fine when this was developed, and I have not worked on this for a while. I have no plans on working on this either. Would it be possible for you to create what is required and issue a pull request? Would be happy to pull in contributions and make this working again.

Regards.

**Comment by GeorgeD19** [comment]
Maybe worth closing this issue.

**Comment by samikrc** [comment]
Indeed - thanks.
